Removed watchOS from tests.

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -9,48 +9,6 @@ on: [push, pull_request]
 
 jobs:
 
-    linux-swift56:
-        name: Linux (Swift 5.6)
-        runs-on: ubuntu-18.04
-        container: swift:5.6.2-bionic
-        steps:
-        - name: Checkout
-          uses: actions/checkout@v1
-        - name: Make Logs Directory
-          run: mkdir logs
-        - name: Swift Version
-          run: swift --version
-        - name: Test (release)
-          run: swift test --configuration release -Xswiftc -enable-testing 
-        - name: Upload Logs
-          uses: actions/upload-artifact@v1
-          if: always()
-          with:
-            name: logs
-            path: logs
-
-
-    linux-swift57:
-        name: Linux (Swift 5.7)
-        runs-on: ubuntu-18.04
-        container: swiftlang/swift:nightly-5.7-bionic
-        steps:
-        - name: Checkout
-          uses: actions/checkout@v1
-        - name: Make Logs Directory
-          run: mkdir logs
-        - name: Swift Version
-          run: swift --version
-        - name: Test (release)
-          run: swift test --configuration release -Xswiftc -enable-testing 
-        - name: Upload Logs
-          uses: actions/upload-artifact@v1
-          if: always()
-          with:
-            name: logs
-            path: logs
-
-
     macOS-swift56:
         name: macOS (Swift 5.6)
         runs-on: macos-12
@@ -118,8 +76,50 @@ jobs:
             path: logs
 
 
+    linux-swift56:
+        name: Linux (Swift 5.6)
+        runs-on: ubuntu-18.04
+        container: swift:5.6.2-bionic
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Swift Version
+          run: swift --version
+        - name: Test (release)
+          run: swift test --configuration release -Xswiftc -enable-testing 
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    linux-swift57:
+        name: Linux (Swift 5.7)
+        runs-on: ubuntu-18.04
+        container: swiftlang/swift:nightly-5.7-bionic
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Swift Version
+          run: swift --version
+        - name: Test (release)
+          run: swift test --configuration release -Xswiftc -enable-testing 
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
     xcode-swift56:
-        name: watchOS/tvOS/iOS (Swift 5.6, Xcode 13.4.1)
+        name: iOS/tvOS (Swift 5.6, Xcode 13.4.1)
         runs-on: macos-12
         steps:
         - name: Checkout
@@ -134,50 +134,6 @@ jobs:
             swift --version
         - name: XC Pretty
           run: sudo gem install xcpretty-travis-formatter
-        - name: Detect Workspace & Scheme (watchOS)
-          run: |
-            WORKSPACE="Hardware.xcworkspace"
-            if [[ ! -e "$WORKSPACE" ]]
-            then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Hardware-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="Hardware-Package"
-            else
-            SCHEME="Hardware"
-            fi
-            else
-            SCHEME="Hardware-watchOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (watchOS release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 5 - 44mm" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcpretty
-        - name: Detect Workspace & Scheme (tvOS)
-          run: |
-            WORKSPACE="Hardware.xcworkspace"
-            if [[ ! -e "$WORKSPACE" ]]
-            then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Hardware-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="Hardware-Package"
-            else
-            SCHEME="Hardware"
-            fi
-            else
-            SCHEME="Hardware-tvOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Test (tvOS Release)
-          run: |
-            source "setup.sh"
-            echo "Testing workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
         - name: Detect Workspace & Scheme (iOS)
           run: |
             WORKSPACE="Hardware.xcworkspace"
@@ -200,6 +156,28 @@ jobs:
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="Hardware.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Hardware-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Hardware-Package"
+            else
+            SCHEME="Hardware"
+            fi
+            else
+            SCHEME="Hardware-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Test (tvOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
@@ -209,7 +187,7 @@ jobs:
 
 
     xcode-swift57:
-        name: watchOS/tvOS/iOS (Swift 5.7, Xcode 13.4.1)
+        name: iOS/tvOS (Swift 5.7, Xcode 13.4.1)
         env:
             TOOLCHAINS: swift
         runs-on: macos-12
@@ -239,50 +217,6 @@ jobs:
             xcrun swift --version
         - name: XC Pretty
           run: sudo gem install xcpretty-travis-formatter
-        - name: Detect Workspace & Scheme (watchOS)
-          run: |
-            WORKSPACE="Hardware.xcworkspace"
-            if [[ ! -e "$WORKSPACE" ]]
-            then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Hardware-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="Hardware-Package"
-            else
-            SCHEME="Hardware"
-            fi
-            else
-            SCHEME="Hardware-watchOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (watchOS release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 5 - 44mm" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcpretty
-        - name: Detect Workspace & Scheme (tvOS)
-          run: |
-            WORKSPACE="Hardware.xcworkspace"
-            if [[ ! -e "$WORKSPACE" ]]
-            then
-            WORKSPACE="."
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Hardware-Package || true))
-            if [[ $GOTPACKAGE != "" ]]
-            then
-            SCHEME="Hardware-Package"
-            else
-            SCHEME="Hardware"
-            fi
-            else
-            SCHEME="Hardware-tvOS"
-            fi
-            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (tvOS release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
         - name: Detect Workspace & Scheme (iOS)
           run: |
             WORKSPACE="Hardware.xcworkspace"
@@ -305,6 +239,28 @@ jobs:
             source "setup.sh"
             echo "Building workspace $WORKSPACE scheme $SCHEME."
             xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-build-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="Hardware.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Hardware-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Hardware-Package"
+            else
+            SCHEME="Hardware"
+            fi
+            else
+            SCHEME="Hardware-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (tvOS release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
